version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
